sonar.projectKey=a22343122a5f9a937345c4efdb8c311bdc8ecf13
sonar.organization=SONAR_TOKEN

sonar.projectName=calculator-cicd-sonarqube
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=test_*.py
sonar.python.version=3.11
